Advent calendar
shopgate-professional-services/ext-advent-calendar pull request #1
Opened 2020-10-27 15:26 UTC by alexbridge

2020-10-28 17:34 UTC, Carsten89 requested changes
i think you should be able to open also days from the past. Lets ask felix/martin

2020-10-28 17:34 UTC, Carsten89 commented on frontend/subscriptions.js
> +      '/advent-calendar',
please create a constants for it and use it in both places

2020-10-28 17:34 UTC, Carsten89 commented on frontend/helpers.js
> +    parseInt(d.day, 10) === parseInt(day, 10)
i don't see a "day" prop in calendar config of the testshop

2020-10-28 17:34 UTC, Carsten89 commented on frontend/pages/AdventCalendar/index.jsx
> +        {isCalendarAllowed() && (
isCalendarAllowed could be stored in a var
not sure how smart js engines are in this case here

2020-10-28 17:34 UTC, Carsten89 commented on frontend/components/ComingSoon/index.jsx
> +      {'Too early message. Come back later in'}
should be configurable

2020-10-28 17:43 UTC, Carsten89 commented on frontend/components/Snowfall/index.jsx
> +const Snowfall = () => (
snowflakes appear sometimes in the middle of the screen and fall from there. 
for me they should always appear at top and fall down from there

also the design looks to me like the snowfall should only be an overlay for the calendar itself and not the complete page

2020-10-29 10:10 UTC, alexbridge commented on frontend/helpers.js
> +    parseInt(d.day, 10) === parseInt(day, 10)
Added to test shop. Its needed since calendar can be configured only for N days and not for all 24 days

2020-11-03 09:58 UTC, merged